languageCode = "en-us"
themesDir = "themes"
publishDir = "docs"
theme = "hugo-theme-shiori"
baseUrl = "https://solienlac.github.io/solienlac/"
canonifyurls = true

title = "SFlink"
author = "Trí Đức"



